'use client'

import { useState } from 'react'
import { Languages, LogOut, MessageCircle, Send, Sparkles } from 'lucide-react'
import { authClient } from '@/lib/auth-client'
import type { Message } from '@/lib/db/schema'

const languages = ['English', 'Hindi', 'Spanish', 'French', 'Japanese', 'Tamil', 'German']

export function Inbox({ messages, userName }: { messages: Message[]; userName: string }) {
  const [selected, setSelected] = useState(messages[0]?.id ?? ''); const [language, setLanguage] = useState('English'); const [translated, setTranslated] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(false)
  const active = messages.find((message) => message.id === selected) ?? messages[0]
  async function translate() { if (!active || language === active.sourceLanguage) return; setLoading(true); const response = await fetch('/api/translate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: active.body, targetLanguage: language }) }); const data = await response.json(); if (data.translation) setTranslated((current) => ({ ...current, [active.id]: data.translation })); setLoading(false) }
  return <main className="inbox-shell"><header className="app-header"><div className="brand-mark"><span className="brand-dot" />polyglot</div><div className="header-actions"><span className="user-greeting">{userName}</span><button className="icon-button" aria-label="Log out" onClick={() => authClient.signOut().then(() => location.href = '/sign-in')}><LogOut size={17} /></button></div></header><div className="inbox-layout"><aside className="conversation-list"><div className="section-label"><span>INBOX</span><span>{messages.length}</span></div>{messages.map((message) => <button key={message.id} className={`conversation ${active?.id === message.id ? 'active' : ''}`} onClick={() => { setSelected(message.id); setTranslated({}) }}><span className="avatar">{message.senderName.charAt(0)}</span><span className="conversation-copy"><strong>{message.senderName}</strong><small>{message.body}</small></span><span className="language-pill">{message.sourceLanguage}</span></button>)}</aside><section className="message-panel">{active ? <><div className="message-header"><div><p className="eyebrow">MESSAGE / {active.sourceLanguage.toUpperCase()}</p><h1>{active.senderName}</h1><p className="handle">{active.senderHandle} · {new Date(active.createdAt).toLocaleDateString()}</p></div><span className="message-index">01</span></div><article className="message-card"><div className="message-meta"><span><MessageCircle size={16} /> Incoming message</span><span>{active.sourceLanguage}</span></div><p className="message-body">{translated[active.id] || active.body}</p>{translated[active.id] && <p className="translated-note"><Sparkles size={14} /> Translated to {language}</p>}</article><div className="translate-bar"><div className="language-control"><Languages size={18} /><label htmlFor="language">Translate to</label><select id="language" value={language} onChange={(event) => setLanguage(event.target.value)}>{languages.map((item) => <option key={item}>{item}</option>)}</select></div><button className="translate-button" onClick={translate} disabled={loading || language === active.sourceLanguage}>{loading ? 'Translating…' : <><Send size={16} /> Translate message</>}</button></div></> : <div className="empty-state"><MessageCircle size={30} /><h2>Your inbox is quiet.</h2><p>Incoming conversations will appear here.</p></div>}</section></div></main>
}
